import { Grievance, GrievanceStatus, GrievanceType, User, UserRole, WorkflowLog, AccountStatus } from './types';

export const MOCK_USERS: User[] = [
  {
    id: 'u1',
    name: 'Alice Student',
    email: 'alice@college.edu',
    password: '123456',
    role: UserRole.STUDENT,
    status: AccountStatus.APPROVED,
    rollNumber: 'CS2024001',
    course: 'B.Tech CSE',
  },
  {
    id: 'u5',
    name: 'Bob Junior',
    email: 'bob.jr@college.edu',
    password: '123456',
    role: UserRole.STUDENT,
    status: AccountStatus.APPROVED,
    rollNumber: 'ME2024102',
    course: 'B.Tech Mechanical',
  },
  {
    id: 'u2',
    name: 'Dr. Smith Reviewer',
    email: 'smith@college.edu',
    password: '123456',
    role: UserRole.FACULTY,
    status: AccountStatus.APPROVED,
    department: 'Computer Science',
  },
  {
    id: 'u3',
    name: 'Prof. Charlie Admin',
    email: 'admin@college.edu',
    password: '123456',
    role: UserRole.ADMIN,
    status: AccountStatus.APPROVED,
  },
  {
    id: 'u4',
    name: 'Dr. Diana Math',
    email: 'diana@college.edu',
    password: '123456',
    role: UserRole.FACULTY,
    status: AccountStatus.APPROVED,
    department: 'Mathematics',
  },
];

// Helper to create a history entry
const createLog = (status: GrievanceStatus, user: string, note?: string, timeOffsetDays = 0): WorkflowLog => ({
  id: Math.random().toString(36).substr(2, 9),
  status,
  updatedBy: user,
  timestamp: new Date(Date.now() - 86400000 * timeOffsetDays).toISOString(),
  note,
});

export const INITIAL_GRIEVANCES: Grievance[] = [
  {
    id: 'GR-1001',
    studentId: 'u1',
    studentName: 'Alice Student',
    studentRoll: 'CS2024001',
    course: 'B.Tech CSE',
    examSession: 'Fall 2023',
    examDate: '2023-12-10',
    subjectCode: 'CS101',
    subjectName: 'Data Structures',
    type: GrievanceType.REVALUATION,
    description: 'I believe I deserved more marks in Question 3 regarding AVL trees. I wrote the correct rotation logic.',
    status: GrievanceStatus.SUBMITTED,
    attachmentUrl: 'docs/answer_script_req.pdf',
    createdAt: new Date(Date.now() - 86400000 * 5).toISOString(),
    updatedAt: new Date(Date.now() - 86400000 * 5).toISOString(),
    history: [
        createLog(GrievanceStatus.SUBMITTED, 'Alice Student', 'Initial submission', 5)
    ],
  },
  {
    id: 'GR-1002',
    studentId: 'u1',
    studentName: 'Alice Student',
    studentRoll: 'CS2024001',
    course: 'B.Tech CSE',
    examSession: 'Fall 2023',
    examDate: '2023-12-12',
    subjectCode: 'MA201',
    subjectName: 'Linear Algebra',
    type: GrievanceType.MISSING_MARKS,
    description: 'My total score is calculated out of 70 instead of 100. Part B marks seem missing.',
    status: GrievanceStatus.IN_REVIEW,
    assignedToFacultyId: 'u4',
    assignedToFacultyName: 'Dr. Diana Math',
    createdAt: new Date(Date.now() - 86400000 * 3).toISOString(),
    updatedAt: new Date(Date.now() - 86400000 * 1).toISOString(),
    history: [
        createLog(GrievanceStatus.SUBMITTED, 'Alice Student', 'Initial submission', 3),
        createLog(GrievanceStatus.ASSIGNED, 'Prof. Charlie Admin', 'Assigned to Dr. Diana', 2),
        createLog(GrievanceStatus.IN_REVIEW, 'Dr. Diana Math', 'Checking answer scripts', 1),
    ],
  },
  {
    id: 'GR-1003',
    studentId: 'u5', 
    studentName: 'Bob Junior',
    studentRoll: 'ME2024102',
    course: 'B.Tech Mech',
    examSession: 'Fall 2023',
    examDate: '2023-12-15',
    subjectCode: 'ME101',
    subjectName: 'Thermodynamics',
    type: GrievanceType.RECOUNTING,
    description: 'Requesting a recount of Section A.',
    status: GrievanceStatus.PENDING_APPROVAL,
    assignedToFacultyId: 'u2',
    assignedToFacultyName: 'Dr. Smith Reviewer',
    facultyFindings: 'Recount done. No change in marks found.',
    createdAt: new Date(Date.now() - 86400000 * 10).toISOString(),
    updatedAt: new Date(Date.now() - 86400000 * 2).toISOString(),
    history: [
        createLog(GrievanceStatus.SUBMITTED, 'Bob Junior', undefined, 10),
        createLog(GrievanceStatus.ASSIGNED, 'Prof. Charlie Admin', undefined, 8),
        createLog(GrievanceStatus.IN_REVIEW, 'Dr. Smith Reviewer', undefined, 5),
        createLog(GrievanceStatus.PENDING_APPROVAL, 'Dr. Smith Reviewer', 'Submission of findings', 2),
    ],
  },
  {
    id: 'GR-1004',
    studentId: 'u5', 
    studentName: 'Bob Junior',
    studentRoll: 'ME2024102',
    course: 'B.Tech Mech',
    examSession: 'Fall 2023',
    examDate: '2023-12-18',
    subjectCode: 'ENG101',
    subjectName: 'Engineering English',
    type: GrievanceType.QP_CORRECTION,
    description: 'Question 5 was out of syllabus.',
    status: GrievanceStatus.RESOLVED,
    finalResolutionNote: 'Agreed. Grace marks awarded to all students.',
    finalMarks: 5,
    createdAt: new Date(Date.now() - 86400000 * 15).toISOString(),
    updatedAt: new Date(Date.now() - 86400000 * 12).toISOString(),
    history: [
        createLog(GrievanceStatus.SUBMITTED, 'Bob Junior', undefined, 15),
        createLog(GrievanceStatus.RESOLVED, 'Prof. Charlie Admin', 'Grace marks awarded', 12),
    ],
  },
];